name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    # services:
      # postgres:
      #   image: postgres
      #   env:
      #     POSTGRES_USER: postgres
      #     POSTGRES_PASSWORD: password
      #     POSTGRES_DB: testdb
      #   ports:
      #     - 5432:5432
      #   options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # - name: Set up Docker Compose
      #   uses: docker/compose-action@v1
      #   with:
      #     compose-file: docker-compose.yml

      - name: Start Docker Compose
        run: docker compose -f docker-compose.yml up --build -d db
        
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      - name: Wait for PostgreSQL to start
        run: docker ps && docker exec db pg_isready --timeout=30

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
